---
- hosts: haproxy
  tasks:
    - name: start docker service
      service:
        name: docker
        state: started
      become: true

    - name: Copy HA-Proxy Config file
      copy:
        src: ./configs/haproxy.cfg
        dest: /home/ec2-user/
        mode: '0777'

    - name: Install HA-Proxy
      yum:
        name: haproxy
        state: present
      become: true

    - name: Start Ha-Proxy
      service:
        name: haproxy
        state: started
      become: true

    - name: Copy file to Ha-Proxy
      template:
        src: /home/ec2-user/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: '0777'
      become: true

    - name: Run node exporter
      community.general.docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"