---
- hosts: Redis-slave-b
  tasks:
    - name: start docker service
      service:
        name: docker
        state: started
      become: true

    - name: Copy Redis Config file
      copy:
        src: ./configs/redis-slave.conf
        dest: /home/ec2-user/
        mode: '0777'

    - name: Copy Sentimel Config file
        copy:
          src: ./configs/sentinel.conf
          dest: /home/ec2-user/
          mode: '0777'

    - name: Run Redis Container
      community.general.docker_container:
        name: Redis
        image: redis
        volumes:
          - /home/ec2-user/redis-slave.conf:/etc/redis/redis.conf
          -  /home/ec2-user/sentinel.conf:/etc/redis/sentinel.conf
        ports:
          - "6379:6379"
        command: "{{ item }}"
        with_item:
          - redis-server /etc/redis/redis.conf
          - redis-server /etc/redis/sentinel.conf
        restart: yes

    - name: Run node exporter
      community.general.docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"