---
- hosts: Web-server
  tasks:
    - name: simple ping
      ping:

    - name: Start docker service
      service:
        name: docker
        state: started
      become: true

    - name: Copy nginx config file
      copy:
        src: ./configs/default.conf
        dest: /home/ec2-user/
        mode: '0777'

    - name: Run Nginx container
      community.general.docker_container:
        name: Nginx
        image: nginx
        volumes:
          - /home/ec2-user/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
        restart: yes