route:
  group_by: ['alertname']
  receiver: smtp-local
receivers:
  - name: 'smtp-local'
    email_configs:
    - to: 'eaglesdonny@gmail.com'
      from: 'jibolaolu@gmail.com'
      require_tls: false
      smarthost: localhost:25
      send_resolved: true