route:
  group_by: [Alertname]
  receiver: email-me
receivers:
- name: email-me
  email_configs:
  - to: jibolaolu@gmail.com
    from: eaglesdonny@gmail.com'
    require_tls: false
    smarthost: smtp.gmail.com:587
    auth_username: "eaglesdonny@gmail.com"
    auth_identity: "eaglesdonny@gmail.com"
    auth_password: "Adiomowo1"
